# Generated by Django 3.1.5 on 2021-01-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebk',
            name='login',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
