# Generated by Django 3.1.5 on 2021-01-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_auto_20210117_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter your email', max_length=254)),
                ('password', models.CharField(help_text='Enter your password', max_length=15)),
            ],
        ),
    ]
