# Generated by Django 3.1.5 on 2021-01-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='entry',
            field=models.TextField(help_text='Type in your entry here', max_length=6000),
        ),
    ]
