# Generated by Django 3.1.5 on 2021-01-17 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_auto_20210117_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebk',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebooks.login'),
        ),
    ]
